#+TITLE: Build Process
#+AUTHOR: Thomas Letan
#+HTML_LINK_UP: index.html

In this chapter, we describe how the Build Process of *~cleopatra~* works, and
how it is implemented in terms of Makefile recipes. Besides, potential users of
*~cleopatra~* will learn how they should structure their generation
processes. We recall that the generation processes *~cleopatra~* uses to build
herself [[file:procs.org][are documented on this very website]].

* ~boot.mk~

#+BEGIN_SRC makefile :tangle boot.mk
ARTIFACTS := build.log
CONFIGURE := .cleopatra
PROCS := $(wildcard ${CLEOPATRA_GENERATION_PROCESSES}/*.org)

init :
	@cleopatra echo "Exporting" "generation process"
	@cleopatra-gen-deps ${PROCS}
	@cleopatra-run-elisp "${CLEOPATRA_DIRECTORY}/emacs.d/cleopatra-gen-proc.el" > build.log

-include ${CLEOPATRA_DIRECTORY}/deps.mk

prebuild :
build : prebuild
postbuild : build
	@cleopatra echo "Updating" ".gitignore"
	@cleopatra-update-gitignore ${CONFIGURE} ${ARTIFACTS}
	@rm ${CLEOPATRA_DIRECTORY}/deps.mk

.PHONY : init prebuild build postbuild
#+END_SRC

*~cleopatra~* leverages the ~postbuild~ phase to delete the ~deps.mk~ file
previously generated during the ~init~ phase. We do that to prevent the
following scenario from happening: one of the generation processes tangles an
invalid Makefile (/e.g./, it contains spaces in place of tabs), which means
~make~ exits without trying to achieve anything… preventing a fixed generation
process to be ever tangled. Since a new ~deps.mk~ file is generated anyway,
keeping it between two builds does not make any sense in any case.

* ~cleopatra-gen-proc.el~

#+BEGIN_SRC emacs-lisp :tangle emacs.d/cleopatra-gen-proc.el :noweb yes :exports none
;;; cleopatra-gen-proc.el --- The cleopatra Emacs Library
;;; Commentary:
;;; Code:
<<cleopatra-gen-proc-el>>

(provide 'cleopatra-gen-proc)
;;; cleopatra-gen-proc.el ends here
#+END_SRC

#+BEGIN_SRC emacs-lisp :noweb-ref cleopatra-gen-proc-el
(defun cleopatra:gen-processes-tangle-publish (conf filename pub-dir)
  (let ((tangled (cleopatra:tangle-publish conf filename pub-dir))
        (proc (file-name-sans-extension (file-name-nondirectory  filename))))
    (with-temp-buffer
      (insert
       (format "include %s.mk\n" proc)
       (format "CONFIGURE += %s\n" (mapconcat 'identity tangled " "))
       (format "prebuild : %s-prebuild\nbuild : %s-build\npostbuild : %s-postbuild\n"
               proc proc proc)
       (format "%s-build : %s-prebuild\n%s-postbuild : %s-build\n"
               proc proc proc proc)
       (format ".PHONY : %s-prebuild %s-build %s-postbuild\n"
               proc proc proc proc))
      (write-file (format "%s/%s.deps.mk" (getenv "CLEOPATRA_DIRECTORY") proc)))))

(cleopatra:configure)

(org-babel-do-load-languages
 'org-babel-load-languages
 '((shell . t)))

(setq org-publish-project-alist
      `(("cleopatra-gen-proc"
         :base-directory ,(getenv "CLEOPATRA_GENERATION_PROCESSES")
         :publishing-directory "."
         :publishing-function cleopatra:gen-processes-tangle-publish)))

(org-publish-all)
#+END_SRC

* ~gen-deps~

#+BEGIN_SRC bash :tangle bin/cleopatra-gen-deps :shebang "#+/bin/bash"
out="${CLEOPATRA_DIRECTORY}/deps.mk"

rm -f "${out}"
touch "${out}"

for proc in "$@"; do
    proc_name=$(basename ${proc} ".org")
    echo "include \${CLEOPATRA_DIRECTORY}/${proc_name}.deps.mk" >> "${out}"
done
#+END_SRC

* ~update-gitignore~

#+BEGIN_SRC bash :tangle bin/cleopatra-update-gitignore :shebang "#+/bin/bash"
BEGIN_MARKER="# begin generated files"
END_MARKER="# end generated files"

# remove the previous list of generated files to ignore
sed -i -e "/${BEGIN_MARKER}/,/${END_MARKER}/d" .gitignore
# remove trailing empty lines
sed -i -e :a -e '/^\n*$/{$d;N;};/\n$/ba' .gitignore

# output the list of files to ignore
echo "" >> .gitignore
echo ${BEGIN_MARKER} >> .gitignore
for f in $@; do
    echo "${f}" >> .gitignore
done
echo ${END_MARKER} >> .gitignore
#+END_SRC
