#+TITLE: Cleopatra Elisp Package
#+AUTHOR: Thomas Letan
#+HTML_LINK_UP: index.html

#+BEGIN_SRC emacs-lisp :tangle cleopatra.el :noweb yes :exports none
;;; cleopatra.el --- The cleopatra Emacs Library
;;; Commentary:
;;; Code:
(require 'package)

<<cleopatra-el>>

(provide 'cleopatra)
;;; cleopatra.el ends here
#+END_SRC

* Init

#+BEGIN_SRC emacs-lisp :noweb-ref cleopatra-el :exports none :noweb yes
(defun cleopatra:init ()
  <<cleopatra-init>>)
#+END_SRC

#+BEGIN_SRC emacs-lisp :noweb-ref cleopatra-el :exports none :noweb yes
(defun cleopatra:ensure-package-installed (&rest packages)
  "Ensure every PACKAGES is installed."
  (mapcar
   (lambda (package)
     (if (package-installed-p package)
         nil
       (package-install package))
     package)
   packages))
#+END_SRC

#+BEGIN_SRC emacs-lisp :noweb-ref cleopatra-init
(setq user-emacs-directory (concat (getenv "ROOT") "/.cleopatra/emacs.d"))
(setq package-user-dir (concat (getenv "ROOT") "/.cleopatra/emacs.d/packages"))

(setq package-archives
      '(("gnu"   . "https://elpa.gnu.org/packages/")
        ("melpa" . "https://melpa.org/packages/")))
(package-initialize)

(or (file-exists-p package-user-dir)
    (package-refresh-contents))

(cleopatra:ensure-package-installed 'use-package)
(eval-when-compile (require 'use-package))
#+END_SRC

#+BEGIN_SRC emacs-lisp :noweb-ref cleopatra-init
(use-package org :ensure t)
(use-package htmlize :ensure t)
#+END_SRC

* Tangling

*~cleopatra~* “tangling semantics” slightly differs from Babel’s default
one. The key difference is that, contrary to Babel, *~cleopatra~* does not force
the structure of your literate sources to match the structure of your tangled
sources.

For instance, let ~IN~ be is the directory wherein lives your literate sources,
~OUT~ be the directory wherein your tangled sources shall be placed, and
~IN/a/b.org~ be a file which contains a source block intended to be tangled in
~c/d.txt~.

  - Babel will assume you want ~d.txt~ to be placed in ~OUT/a/c/~, that is
    to reflect the fact that ~b.org~ lives in ~a~
  - *~cleopatra~* won’t, and ~d.txt~ will be placed in ~OUT/c/~

** =cleopatra-tangle-publish=

=cleopatra-tangle-publish= is a function to be used with =org-publish=. To
implement the desire behavior, it does not use the third argument (which is
updated by Babel to take into account the structure of the literate programming
source), but we rather use the first argument which contains the component
configuration, and this configuration needs to contains a field
~:publishing-directory~.

#+BEGIN_SRC emacs-lisp :noweb-ref cleopatra-el
(defun cleopatra:tangle-publish (conf filename _pub-dir)
  (let ((pub-dir (plist-get conf :publishing-directory)))
    (if pub-dir
        (with-temp-buffer
          (find-file-read-only filename)
          (unless (file-exists-p pub-dir)
            (make-directory pub-dir))
          (cd (getenv "ROOT"))
          (cd pub-dir)
          (org-babel-tangle))
      (error "cleopatra: missing :publishing-directory option"))))
#+END_SRC

** TODO =cleopatra-gen-processes-tangle-publish=

#+BEGIN_SRC emacs-lisp :noweb-ref cleopatra-el
(defun cleopatra:gen-processes-tangle-publish (conf filename pub-dir)
  (let ((tangled (cleopatra-tangle-publish conf filename pub-dir)))
    (print "TODO: generate dependency files")))
#+END_SRC

* The ~cleopatra-emacs~ Binary

To generation processes, we provide ~cleopatra-emacs~, to be called from within
a *~cleopatra~* execution context. ~cleopatra-emacs~ is intended to be used
using the ~--script~ command-line argument to execute Emacs lisp script with the
proper configuration (in particular, with ~cleopatra.el~ loaded). But it can
also be used as-is to use the exact same Emacs that is being used for exporting
and tangling (this may be useful for debugging).

#+BEGIN_SRC bash :tangle bin/cleopatra-emacs :shebang "#!/bin/sh"
emacs -Q \
      --load="${ROOT}/.cleopatra/emacs.d/cleopatra.el" \
      --eval="(cleopatra:init)"
#+END_SRC
